### PR TITLE
Load credentials on local agent to be used on remote (Fixes #21)

### LINKED ISSUE #21: Credentials loaded on remote agent fails
Credentials for a remote agent are incorrectly loaded inside the remote call. This results in the following exception:

> ERROR: Build step failed with exception
> com.google.jenkins.plugins.credentials.oauth.GoogleRobotPrivateKeyCredentials$AccountIdNotSetException
>     at com.google.jenkins.plugins.credentials.oauth.GoogleRobotPrivateKeyCredentials.getUsername(GoogleRobotPrivateKeyCredentials.java:152)
>     at com.google.jenkins.plugins.credentials.oauth.RemotableGoogleCredentials.<init>(RemotableGoogleCredentials.java:54)
>     at com.google.jenkins.plugins.credentials.oauth.GoogleRobotCredentials.forRemote(GoogleRobotCredentials.java:204)
>     at com.google.jenkins.plugins.storage.AbstractUpload.performUploads(AbstractUpload.java:413)
>     at com.google.jenkins.plugins.storage.AbstractUpload.access$000(AbstractUpload.java:101)
>     at com.google.jenkins.plugins.storage.AbstractUpload$1.call(AbstractUpload.java:367)
>     at com.google.jenkins.plugins.storage.AbstractUpload$1.call(AbstractUpload.java:364)
>     at hudson.remoting.UserRequest.perform(UserRequest.java:153)
>     at hudson.remoting.UserRequest.perform(UserRequest.java:50)
>     at hudson.remoting.Request$2.run(Request.java:332)
>     at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at hudson.remoting.Engine$1$1.run(Engine.java:85)
>     at java.lang.Thread.run(Thread.java:745)
>     at ......remote call to jenkins-slave-395f7dbfa981b(Native Method)
>     at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
>     at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
>     at hudson.remoting.Channel.call(Channel.java:781)
>     at hudson.FilePath.act(FilePath.java:1102)
>     at com.google.jenkins.plugins.storage.AbstractUpload.initiateUploadsAtWorkspace(AbstractUpload.java:363)
>     at com.google.jenkins.plugins.storage.AbstractUpload.perform(AbstractUpload.java:182)
>     at com.google.jenkins.plugins.storage.GoogleCloudStorageUploader.perform(GoogleCloudStorageUploader.java:109)
>     at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
>     at hudson.model.Build$BuildExecution.post2(Build.java:185)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
>     at hudson.model.Run.execute(Run.java:1766)
>     at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
>     at hudson.model.ResourceController.execute(ResourceController.java:98)
>     at hudson.model.Executor.run(Executor.java:410)

### PR DESCRIPTION
**Pull request by wnagele**

### CODE REVIEW

**Comment by linux-samurai** [comment]
I also am encountering this issue. the plugin works great on the 'master', but failing on remote slaves. Would be great to get this merged in and built versus having to run a custom, one-off, version of the plugin.

**Comment by wnagele** [comment]
Anybody able to merge and release this? @astroilov

**Comment by jeunito** [comment]
We are also encountering this issue.

**Comment by wnagele** [comment]
Is anybody still maintaining this plugin? @mattmoor @tcnghia @astroilov

**Comment by wnagele** [comment]
@linux-samurai @jeunito - if you feel like adopting this plugin you could follow the process (https://wiki.jenkins-ci.org/display/JENKINS/Adopt+a+Plugin) and get this resolved.

**Comment by Archonoid** [comment]
Hi,

Apologies for the long delay. I'll take a look at this PR.

**Comment by astroilov** [comment]
Hi,

Apologies for the long delay. I'll take a look at this PR.

**Comment by astroilov** [comment]
The PR code looks good. However, we do require that authors of contributing code sign a contributor license agreement (CLA). You (or your employer) retain the copyright to your contribution,
this simply gives us permission to use and redistribute your contributions as
part of the project. It looks like you don't yet have a CLA on file; you can do so easily at https://cla.developers.google.com/. Alternately, if you should already have a CLA, let me know and I'll investigate further.

I'll be happy to approve and merge this PR once that is handled. I can then also push a new release of the plugin.

**Comment by wnagele** [comment]
Should be ok now - I had signed the CLA back in 2011 but the GitHub account wasn't set on it. You can try again now.

**Comment by astroilov** [comment]
Yep, I see it now. Thanks!

**Comment by wnagele** [comment]
Can you please also do a release for this? Thanks!

**Comment by astroilov** [comment]
Version 0.13 should now be available.

**Comment by wnagele** [comment]
Great - Thanks!

**Comment by jeunito** [comment]
Thanks for the merge.

**Pull request merged**
