### PR TITLE
JENKINS-47287: Fix download URL

### PR DESCRIPTION
**Pull request by tpatja-broadsoft**
Use access control aware URL for download link.

[FIXES JENKINS-47287]

### CODE REVIEW

**Comment by agoulti** [comment]
Thanks for raising the issue and fixing it!

**Comment by agoulti** [comment]
I am in the middle of adding new functionality: classicUpload is now available as a build step and in pipeline, and I'm working on adding Download.
I'm hoping to have it done within about a week and release as a new major version some time next week.

Let me know if you'd like this sooner and I could look into doing a release without all the pieces in place.

**Comment by tpatja-broadsoft** [comment]
Thanks for the update. Next week will be fine.

**Comment by agoulti** [comment]
The download functionality is a bit delayed, so I've one a minor version release today. It should come live within ~8hours

**Pull request merged**
